// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard,
// UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
// We also try to prevent mixing versions of shared uniffi header structs.
// If you add anything to the #else block, you must increment the version suffix
// in UNIFFI_SHARED_HEADER_V4
#ifndef UNIFFI_SHARED_HEADER_V4
#error Combining helper code from multiple versions of uniffi is not supported
#endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def
// UNIFFI_SHARED_H`) you *must* ⚠️ ⚠️ increment the version suffix in all
// instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer {
  uint64_t capacity;
  uint64_t len;
  uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes {
  int32_t len;
  const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
  int8_t code;
  RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def
// UNIFFI_SHARED_H`) you *must* ⚠️ ⚠️ increment the version suffix in all
// instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t);

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t);

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t);

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t);

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
  uint64_t handle;
  UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
  uint8_t returnValue;
  RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t,
                                              UniffiForeignFutureResultU8);

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
  int8_t returnValue;
  RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t,
                                              UniffiForeignFutureResultI8);

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
  uint16_t returnValue;
  RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t,
                                               UniffiForeignFutureResultU16);

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
  int16_t returnValue;
  RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t,
                                               UniffiForeignFutureResultI16);

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
  uint32_t returnValue;
  RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t,
                                               UniffiForeignFutureResultU32);

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
  int32_t returnValue;
  RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t,
                                               UniffiForeignFutureResultI32);

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
  uint64_t returnValue;
  RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t,
                                               UniffiForeignFutureResultU64);

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
  int64_t returnValue;
  RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t,
                                               UniffiForeignFutureResultI64);

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
  float returnValue;
  RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t,
                                               UniffiForeignFutureResultF32);

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
  double returnValue;
  RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t,
                                               UniffiForeignFutureResultF64);

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
  RustBuffer returnValue;
  RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(
    uint64_t, UniffiForeignFutureResultRustBuffer);

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
  RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t,
                                                UniffiForeignFutureResultVoid);

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CLONE_NATIVEIMPORTEDPLAYBACKLEASE
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CLONE_NATIVEIMPORTEDPLAYBACKLEASE
uint64_t uniffi_open_scribe_uniffi_fn_clone_nativeimportedplaybacklease(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FREE_NATIVEIMPORTEDPLAYBACKLEASE
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FREE_NATIVEIMPORTEDPLAYBACKLEASE
void uniffi_open_scribe_uniffi_fn_free_nativeimportedplaybacklease(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVEIMPORTEDPLAYBACKLEASE_PLAYBACK_PATH
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVEIMPORTEDPLAYBACKLEASE_PLAYBACK_PATH
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativeimportedplaybacklease_playback_path(
    uint64_t ptr, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CLONE_NATIVERECORDINGPREPARATION
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CLONE_NATIVERECORDINGPREPARATION
uint64_t uniffi_open_scribe_uniffi_fn_clone_nativerecordingpreparation(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FREE_NATIVERECORDINGPREPARATION
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FREE_NATIVERECORDINGPREPARATION
void uniffi_open_scribe_uniffi_fn_free_nativerecordingpreparation(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CONSTRUCTOR_NATIVERECORDINGPREPARATION_OPEN
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CONSTRUCTOR_NATIVERECORDINGPREPARATION_OPEN
uint64_t
uniffi_open_scribe_uniffi_fn_constructor_nativerecordingpreparation_open(
    RustBuffer managed_root, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_ABANDON_RESERVED_SEGMENT
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_ABANDON_RESERVED_SEGMENT
void uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_abandon_reserved_segment(
    uint64_t ptr, RustBuffer session_id, RustBuffer segment_id,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_ACCEPT_FIRST_SAMPLE
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_ACCEPT_FIRST_SAMPLE
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_accept_first_sample(
    uint64_t ptr, RustBuffer receipt, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_ACCEPT_MEDIA_OPEN
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_ACCEPT_MEDIA_OPEN
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_accept_media_open(
    uint64_t ptr, RustBuffer receipt, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_ACCEPT_MIXDOWN
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_ACCEPT_MIXDOWN
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_accept_mixdown(
    uint64_t ptr, RustBuffer receipt, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_ANCHOR_CAPTURE_CLOCK
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_ANCHOR_CAPTURE_CLOCK
void uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_anchor_capture_clock(
    uint64_t ptr, RustBuffer session_id, uint64_t host_anchor,
    uint32_t numerator, uint32_t denominator,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_AUTHORIZE_INITIAL_MEDIA
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_AUTHORIZE_INITIAL_MEDIA
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_authorize_initial_media(
    uint64_t ptr, RustBuffer session_id, RustBuffer source_kind,
    RustBuffer source_display_name, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_AUTHORIZE_MIXDOWN
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_AUTHORIZE_MIXDOWN
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_authorize_mixdown(
    uint64_t ptr, RustBuffer session_id, uint64_t available_bytes,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_AUTHORIZE_NEXT_SEGMENT
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_AUTHORIZE_NEXT_SEGMENT
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_authorize_next_segment(
    uint64_t ptr, RustBuffer session_id, RustBuffer previous_segment_id,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_CONFIRM_RECORDING
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_CONFIRM_RECORDING
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_confirm_recording(
    uint64_t ptr, RustBuffer session_id, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_IMPORT_COMPRESSED_M4A
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_IMPORT_COMPRESSED_M4A
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_import_compressed_m4a(
    uint64_t ptr, RustBuffer title, RustBuffer source_path, RustBuffer metadata,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_IMPORT_NORMALIZED_CAF
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_IMPORT_NORMALIZED_CAF
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_import_normalized_caf(
    uint64_t ptr, RustBuffer title, RustBuffer normalized_path,
    RustBuffer original, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_IMPORT_RECOVERABLE_CAF
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_IMPORT_RECOVERABLE_CAF
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_import_recoverable_caf(
    uint64_t ptr, RustBuffer title, RustBuffer source_path,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_INTERRUPT_SESSION
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_INTERRUPT_SESSION
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_interrupt_session(
    uint64_t ptr, RustBuffer session_id, RustBuffer reason,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_LEASE_IMPORTED_PLAYBACK
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_LEASE_IMPORTED_PLAYBACK
uint64_t
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_lease_imported_playback(
    uint64_t ptr, RustBuffer session_id, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_LEASE_RECOVERED_PLAYBACK
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_LEASE_RECOVERED_PLAYBACK
uint64_t
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_lease_recovered_playback(
    uint64_t ptr, RustBuffer session_id, RustBuffer source_id,
    RustBuffer track_id, RustBuffer segment_id,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_LEASE_VALIDATED_MIXDOWN
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_LEASE_VALIDATED_MIXDOWN
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_lease_validated_mixdown(
    uint64_t ptr, RustBuffer session_id, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_PLAYBACK_TIMELINE
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_PLAYBACK_TIMELINE
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_playback_timeline(
    uint64_t ptr, RustBuffer session_id, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_PREPARE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_PREPARE_SESSION
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_prepare_session(
    uint64_t ptr, RustBuffer title, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_PREPARE_SESSION_WITH_REQUIRED_SOURCES
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_PREPARE_SESSION_WITH_REQUIRED_SOURCES
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_prepare_session_with_required_sources(
    uint64_t ptr, RustBuffer title, RustBuffer required_sources,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_RECORD_SOURCE_FAILURE
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_RECORD_SOURCE_FAILURE
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_record_source_failure(
    uint64_t ptr, RustBuffer session_id, RustBuffer source_kind,
    RustBuffer reason, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_RECOVER_PLAYABLE_SESSIONS
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_RECOVER_PLAYABLE_SESSIONS
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_recover_playable_sessions(
    uint64_t ptr, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_RUNTIME_LIBRARY_SNAPSHOT
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_RUNTIME_LIBRARY_SNAPSHOT
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_runtime_library_snapshot(
    uint64_t ptr, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_SEAL_SEGMENT
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_SEAL_SEGMENT
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_seal_segment(
    uint64_t ptr, RustBuffer receipt, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_VALIDATED_MIXDOWN
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_VALIDATED_MIXDOWN
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_validated_mixdown(
    uint64_t ptr, RustBuffer session_id, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_RECORDER_ACTION
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_RECORDER_ACTION
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_recorder_action(
    uint64_t ptr, RustBuffer session_id, RustBuffer action,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_RECORDER_DETAIL
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVERECORDINGPREPARATION_RECORDER_DETAIL
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativerecordingpreparation_recorder_detail(
    uint64_t ptr, RustBuffer session_id, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CLONE_NATIVETIMELINEMEDIA
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CLONE_NATIVETIMELINEMEDIA
uint64_t uniffi_open_scribe_uniffi_fn_clone_nativetimelinemedia(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FREE_NATIVETIMELINEMEDIA
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FREE_NATIVETIMELINEMEDIA
void uniffi_open_scribe_uniffi_fn_free_nativetimelinemedia(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETIMELINEMEDIA_LEASE
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETIMELINEMEDIA_LEASE
uint64_t uniffi_open_scribe_uniffi_fn_method_nativetimelinemedia_lease(
    uint64_t ptr, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CLONE_NATIVESPEECHMODELS
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CLONE_NATIVESPEECHMODELS
uint64_t uniffi_open_scribe_uniffi_fn_clone_nativespeechmodels(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FREE_NATIVESPEECHMODELS
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FREE_NATIVESPEECHMODELS
void uniffi_open_scribe_uniffi_fn_free_nativespeechmodels(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CONSTRUCTOR_NATIVESPEECHMODELS_OPEN
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CONSTRUCTOR_NATIVESPEECHMODELS_OPEN
uint64_t uniffi_open_scribe_uniffi_fn_constructor_nativespeechmodels_open(
    RustBuffer managed_root, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVESPEECHMODELS_INSTALL_FROM_FILE
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVESPEECHMODELS_INSTALL_FROM_FILE
void uniffi_open_scribe_uniffi_fn_method_nativespeechmodels_install_from_file(
    uint64_t ptr, RustBuffer model_id, RustBuffer source_path,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVESPEECHMODELS_MODELS
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVESPEECHMODELS_MODELS
RustBuffer uniffi_open_scribe_uniffi_fn_method_nativespeechmodels_models(
    uint64_t ptr, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVESPEECHMODELS_NEEDS_DECODED_COMPANION
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVESPEECHMODELS_NEEDS_DECODED_COMPANION
int8_t
uniffi_open_scribe_uniffi_fn_method_nativespeechmodels_needs_decoded_companion(
    uint64_t ptr, RustBuffer session_id, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVESPEECHMODELS_TRANSCRIBE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVESPEECHMODELS_TRANSCRIBE_SESSION
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativespeechmodels_transcribe_session(
    uint64_t ptr, RustBuffer model_id, RustBuffer session_id,
    RustBuffer decoded_companion_path, uint64_t job,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CLONE_NATIVETRANSCRIPTIONJOB
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CLONE_NATIVETRANSCRIPTIONJOB
uint64_t uniffi_open_scribe_uniffi_fn_clone_nativetranscriptionjob(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FREE_NATIVETRANSCRIPTIONJOB
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FREE_NATIVETRANSCRIPTIONJOB
void uniffi_open_scribe_uniffi_fn_free_nativetranscriptionjob(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CONSTRUCTOR_NATIVETRANSCRIPTIONJOB_NEW
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CONSTRUCTOR_NATIVETRANSCRIPTIONJOB_NEW
uint64_t uniffi_open_scribe_uniffi_fn_constructor_nativetranscriptionjob_new(
    RustCallStatus *_Nonnull out_status

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTIONJOB_CANCEL
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTIONJOB_CANCEL
void uniffi_open_scribe_uniffi_fn_method_nativetranscriptionjob_cancel(
    uint64_t ptr, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTIONJOB_IS_CANCELLED
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTIONJOB_IS_CANCELLED
int8_t uniffi_open_scribe_uniffi_fn_method_nativetranscriptionjob_is_cancelled(
    uint64_t ptr, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTIONJOB_PROGRESS
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTIONJOB_PROGRESS
RustBuffer uniffi_open_scribe_uniffi_fn_method_nativetranscriptionjob_progress(
    uint64_t ptr, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CLONE_NATIVETRANSCRIPTLIBRARY
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CLONE_NATIVETRANSCRIPTLIBRARY
uint64_t uniffi_open_scribe_uniffi_fn_clone_nativetranscriptlibrary(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FREE_NATIVETRANSCRIPTLIBRARY
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FREE_NATIVETRANSCRIPTLIBRARY
void uniffi_open_scribe_uniffi_fn_free_nativetranscriptlibrary(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CONSTRUCTOR_NATIVETRANSCRIPTLIBRARY_OPEN
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_CONSTRUCTOR_NATIVETRANSCRIPTLIBRARY_OPEN
uint64_t uniffi_open_scribe_uniffi_fn_constructor_nativetranscriptlibrary_open(
    RustBuffer managed_root, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_ABANDON_DELETION
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_ABANDON_DELETION
void uniffi_open_scribe_uniffi_fn_method_nativetranscriptlibrary_abandon_deletion(
    uint64_t ptr, RustBuffer session_id, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_AUDIO_EXPORT_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_AUDIO_EXPORT_OPTIONS
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativetranscriptlibrary_audio_export_options(
    uint64_t ptr, RustBuffer session_id, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_AVAILABILITY
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_AVAILABILITY
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativetranscriptlibrary_availability(
    uint64_t ptr, RustBuffer session_id, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_BEGIN_DELETION
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_BEGIN_DELETION
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativetranscriptlibrary_begin_deletion(
    uint64_t ptr, RustBuffer session_id, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_COMPLETE_DELETION
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_COMPLETE_DELETION
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativetranscriptlibrary_complete_deletion(
    uint64_t ptr, RustBuffer session_id, RustBuffer trash_reference,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_CORRECT_SEGMENT
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_CORRECT_SEGMENT
void uniffi_open_scribe_uniffi_fn_method_nativetranscriptlibrary_correct_segment(
    uint64_t ptr, RustBuffer session_id, RustBuffer revision_id,
    uint32_t sequence, RustBuffer text, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_DOCUMENT
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_DOCUMENT
RustBuffer uniffi_open_scribe_uniffi_fn_method_nativetranscriptlibrary_document(
    uint64_t ptr, RustBuffer session_id, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT
RustBuffer uniffi_open_scribe_uniffi_fn_method_nativetranscriptlibrary_export(
    uint64_t ptr, RustBuffer session_id, RustBuffer format,
    RustBuffer destination_path, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_ORIGINAL_MEDIA
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_ORIGINAL_MEDIA
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativetranscriptlibrary_export_original_media(
    uint64_t ptr, RustBuffer session_id, RustBuffer destination_path,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_PORTABLE_PACKAGE
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_PORTABLE_PACKAGE
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativetranscriptlibrary_export_portable_package(
    uint64_t ptr, RustBuffer session_id, RustBuffer destination_path,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_SESSION_MANIFEST
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_SESSION_MANIFEST
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativetranscriptlibrary_export_session_manifest(
    uint64_t ptr, RustBuffer session_id, RustBuffer destination_path,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_TRACK_WAV
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_TRACK_WAV
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativetranscriptlibrary_export_track_wav(
    uint64_t ptr, RustBuffer session_id, RustBuffer track_id,
    RustBuffer destination_path, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_VALIDATED_MIX
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_VALIDATED_MIX
RustBuffer
uniffi_open_scribe_uniffi_fn_method_nativetranscriptlibrary_export_validated_mix(
    uint64_t ptr, RustBuffer session_id, RustBuffer destination_path,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_RENAME_SPEAKER
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_RENAME_SPEAKER
void uniffi_open_scribe_uniffi_fn_method_nativetranscriptlibrary_rename_speaker(
    uint64_t ptr, RustBuffer session_id, RustBuffer track_id, RustBuffer label,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_SEARCH
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_SEARCH
RustBuffer uniffi_open_scribe_uniffi_fn_method_nativetranscriptlibrary_search(
    uint64_t ptr, RustBuffer query, RustBuffer session_id, uint32_t limit,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_SPEAKERS
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_METHOD_NATIVETRANSCRIPTLIBRARY_SPEAKERS
RustBuffer uniffi_open_scribe_uniffi_fn_method_nativetranscriptlibrary_speakers(
    uint64_t ptr, RustBuffer session_id, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FUNC_NATIVE_APPLY_FIXTURE_COMMAND
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FUNC_NATIVE_APPLY_FIXTURE_COMMAND
RustBuffer uniffi_open_scribe_uniffi_fn_func_native_apply_fixture_command(
    RustBuffer fixture, RustBuffer command,
    RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FUNC_NATIVE_FIXTURE
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FUNC_NATIVE_FIXTURE
RustBuffer uniffi_open_scribe_uniffi_fn_func_native_fixture(
    RustBuffer fixture, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FUNC_NATIVE_FIXTURE_CATALOG
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FUNC_NATIVE_FIXTURE_CATALOG
RustBuffer uniffi_open_scribe_uniffi_fn_func_native_fixture_catalog(
    RustCallStatus *_Nonnull out_status

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FUNC_NATIVE_IMPORT_POLICY
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FUNC_NATIVE_IMPORT_POLICY
RustBuffer uniffi_open_scribe_uniffi_fn_func_native_import_policy(
    RustCallStatus *_Nonnull out_status

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FUNC_NATIVE_STATUS
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FUNC_NATIVE_STATUS
RustBuffer uniffi_open_scribe_uniffi_fn_func_native_status(
    RustCallStatus *_Nonnull out_status

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FUNC_VERIFY_PORTABLE_PACKAGE
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_FN_FUNC_VERIFY_PORTABLE_PACKAGE
RustBuffer uniffi_open_scribe_uniffi_fn_func_verify_portable_package(
    RustBuffer package_path, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUSTBUFFER_ALLOC
RustBuffer
ffi_open_scribe_uniffi_rustbuffer_alloc(uint64_t size,
                                        RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_open_scribe_uniffi_rustbuffer_from_bytes(
    ForeignBytes bytes, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUSTBUFFER_FREE
void ffi_open_scribe_uniffi_rustbuffer_free(
    RustBuffer buf, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUSTBUFFER_RESERVE
RustBuffer
ffi_open_scribe_uniffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional,
                                          RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_U8
void ffi_open_scribe_uniffi_rust_future_poll_u8(
    uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback,
    uint64_t callback_data);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_U8
void ffi_open_scribe_uniffi_rust_future_cancel_u8(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_U8
void ffi_open_scribe_uniffi_rust_future_free_u8(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_open_scribe_uniffi_rust_future_complete_u8(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_I8
void ffi_open_scribe_uniffi_rust_future_poll_i8(
    uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback,
    uint64_t callback_data);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_I8
void ffi_open_scribe_uniffi_rust_future_cancel_i8(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_I8
void ffi_open_scribe_uniffi_rust_future_free_i8(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_open_scribe_uniffi_rust_future_complete_i8(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_U16
void ffi_open_scribe_uniffi_rust_future_poll_u16(
    uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback,
    uint64_t callback_data);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_U16
void ffi_open_scribe_uniffi_rust_future_cancel_u16(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_U16
void ffi_open_scribe_uniffi_rust_future_free_u16(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_open_scribe_uniffi_rust_future_complete_u16(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_I16
void ffi_open_scribe_uniffi_rust_future_poll_i16(
    uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback,
    uint64_t callback_data);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_I16
void ffi_open_scribe_uniffi_rust_future_cancel_i16(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_I16
void ffi_open_scribe_uniffi_rust_future_free_i16(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_open_scribe_uniffi_rust_future_complete_i16(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_U32
void ffi_open_scribe_uniffi_rust_future_poll_u32(
    uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback,
    uint64_t callback_data);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_U32
void ffi_open_scribe_uniffi_rust_future_cancel_u32(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_U32
void ffi_open_scribe_uniffi_rust_future_free_u32(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_open_scribe_uniffi_rust_future_complete_u32(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_I32
void ffi_open_scribe_uniffi_rust_future_poll_i32(
    uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback,
    uint64_t callback_data);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_I32
void ffi_open_scribe_uniffi_rust_future_cancel_i32(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_I32
void ffi_open_scribe_uniffi_rust_future_free_i32(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_open_scribe_uniffi_rust_future_complete_i32(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_U64
void ffi_open_scribe_uniffi_rust_future_poll_u64(
    uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback,
    uint64_t callback_data);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_U64
void ffi_open_scribe_uniffi_rust_future_cancel_u64(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_U64
void ffi_open_scribe_uniffi_rust_future_free_u64(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_open_scribe_uniffi_rust_future_complete_u64(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_I64
void ffi_open_scribe_uniffi_rust_future_poll_i64(
    uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback,
    uint64_t callback_data);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_I64
void ffi_open_scribe_uniffi_rust_future_cancel_i64(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_I64
void ffi_open_scribe_uniffi_rust_future_free_i64(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_open_scribe_uniffi_rust_future_complete_i64(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_F32
void ffi_open_scribe_uniffi_rust_future_poll_f32(
    uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback,
    uint64_t callback_data);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_F32
void ffi_open_scribe_uniffi_rust_future_cancel_f32(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_F32
void ffi_open_scribe_uniffi_rust_future_free_f32(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_F32
float ffi_open_scribe_uniffi_rust_future_complete_f32(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_F64
void ffi_open_scribe_uniffi_rust_future_poll_f64(
    uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback,
    uint64_t callback_data);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_F64
void ffi_open_scribe_uniffi_rust_future_cancel_f64(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_F64
void ffi_open_scribe_uniffi_rust_future_free_f64(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_F64
double ffi_open_scribe_uniffi_rust_future_complete_f64(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_open_scribe_uniffi_rust_future_poll_rust_buffer(
    uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback,
    uint64_t callback_data);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_open_scribe_uniffi_rust_future_cancel_rust_buffer(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_open_scribe_uniffi_rust_future_free_rust_buffer(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_open_scribe_uniffi_rust_future_complete_rust_buffer(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_POLL_VOID
void ffi_open_scribe_uniffi_rust_future_poll_void(
    uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback,
    uint64_t callback_data);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_CANCEL_VOID
void ffi_open_scribe_uniffi_rust_future_cancel_void(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_FREE_VOID
void ffi_open_scribe_uniffi_rust_future_free_void(uint64_t handle);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_RUST_FUTURE_COMPLETE_VOID
void ffi_open_scribe_uniffi_rust_future_complete_void(
    uint64_t handle, RustCallStatus *_Nonnull out_status);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_FUNC_NATIVE_APPLY_FIXTURE_COMMAND
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_FUNC_NATIVE_APPLY_FIXTURE_COMMAND
uint16_t
uniffi_open_scribe_uniffi_checksum_func_native_apply_fixture_command(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_FUNC_NATIVE_FIXTURE
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_FUNC_NATIVE_FIXTURE
uint16_t uniffi_open_scribe_uniffi_checksum_func_native_fixture(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_FUNC_NATIVE_FIXTURE_CATALOG
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_FUNC_NATIVE_FIXTURE_CATALOG
uint16_t uniffi_open_scribe_uniffi_checksum_func_native_fixture_catalog(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_FUNC_NATIVE_IMPORT_POLICY
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_FUNC_NATIVE_IMPORT_POLICY
uint16_t uniffi_open_scribe_uniffi_checksum_func_native_import_policy(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_FUNC_NATIVE_STATUS
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_FUNC_NATIVE_STATUS
uint16_t uniffi_open_scribe_uniffi_checksum_func_native_status(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_FUNC_VERIFY_PORTABLE_PACKAGE
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_FUNC_VERIFY_PORTABLE_PACKAGE
uint16_t uniffi_open_scribe_uniffi_checksum_func_verify_portable_package(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVEIMPORTEDPLAYBACKLEASE_PLAYBACK_PATH
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVEIMPORTEDPLAYBACKLEASE_PLAYBACK_PATH
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativeimportedplaybacklease_playback_path(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_ABANDON_RESERVED_SEGMENT
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_ABANDON_RESERVED_SEGMENT
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_abandon_reserved_segment(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_ACCEPT_FIRST_SAMPLE
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_ACCEPT_FIRST_SAMPLE
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_accept_first_sample(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_ACCEPT_MEDIA_OPEN
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_ACCEPT_MEDIA_OPEN
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_accept_media_open(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_ACCEPT_MIXDOWN
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_ACCEPT_MIXDOWN
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_accept_mixdown(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_ANCHOR_CAPTURE_CLOCK
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_ANCHOR_CAPTURE_CLOCK
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_anchor_capture_clock(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_AUTHORIZE_INITIAL_MEDIA
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_AUTHORIZE_INITIAL_MEDIA
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_authorize_initial_media(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_AUTHORIZE_MIXDOWN
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_AUTHORIZE_MIXDOWN
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_authorize_mixdown(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_AUTHORIZE_NEXT_SEGMENT
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_AUTHORIZE_NEXT_SEGMENT
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_authorize_next_segment(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_CONFIRM_RECORDING
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_CONFIRM_RECORDING
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_confirm_recording(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_IMPORT_COMPRESSED_M4A
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_IMPORT_COMPRESSED_M4A
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_import_compressed_m4a(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_IMPORT_NORMALIZED_CAF
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_IMPORT_NORMALIZED_CAF
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_import_normalized_caf(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_IMPORT_RECOVERABLE_CAF
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_IMPORT_RECOVERABLE_CAF
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_import_recoverable_caf(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_INTERRUPT_SESSION
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_INTERRUPT_SESSION
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_interrupt_session(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_LEASE_IMPORTED_PLAYBACK
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_LEASE_IMPORTED_PLAYBACK
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_lease_imported_playback(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_LEASE_RECOVERED_PLAYBACK
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_LEASE_RECOVERED_PLAYBACK
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_lease_recovered_playback(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_LEASE_VALIDATED_MIXDOWN
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_LEASE_VALIDATED_MIXDOWN
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_lease_validated_mixdown(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_PLAYBACK_TIMELINE
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_PLAYBACK_TIMELINE
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_playback_timeline(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_PREPARE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_PREPARE_SESSION
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_prepare_session(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_PREPARE_SESSION_WITH_REQUIRED_SOURCES
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_PREPARE_SESSION_WITH_REQUIRED_SOURCES
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_prepare_session_with_required_sources(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_RECORD_SOURCE_FAILURE
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_RECORD_SOURCE_FAILURE
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_record_source_failure(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_RECOVER_PLAYABLE_SESSIONS
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_RECOVER_PLAYABLE_SESSIONS
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_recover_playable_sessions(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_RUNTIME_LIBRARY_SNAPSHOT
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_RUNTIME_LIBRARY_SNAPSHOT
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_runtime_library_snapshot(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_SEAL_SEGMENT
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_SEAL_SEGMENT
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_seal_segment(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_VALIDATED_MIXDOWN
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_VALIDATED_MIXDOWN
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_validated_mixdown(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_RECORDER_ACTION
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_RECORDER_ACTION
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_recorder_action(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_RECORDER_DETAIL
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVERECORDINGPREPARATION_RECORDER_DETAIL
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativerecordingpreparation_recorder_detail(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETIMELINEMEDIA_LEASE
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETIMELINEMEDIA_LEASE
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetimelinemedia_lease(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVESPEECHMODELS_INSTALL_FROM_FILE
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVESPEECHMODELS_INSTALL_FROM_FILE
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativespeechmodels_install_from_file(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVESPEECHMODELS_MODELS
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVESPEECHMODELS_MODELS
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativespeechmodels_models(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVESPEECHMODELS_NEEDS_DECODED_COMPANION
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVESPEECHMODELS_NEEDS_DECODED_COMPANION
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativespeechmodels_needs_decoded_companion(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVESPEECHMODELS_TRANSCRIBE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVESPEECHMODELS_TRANSCRIBE_SESSION
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativespeechmodels_transcribe_session(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTIONJOB_CANCEL
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTIONJOB_CANCEL
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptionjob_cancel(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTIONJOB_IS_CANCELLED
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTIONJOB_IS_CANCELLED
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptionjob_is_cancelled(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTIONJOB_PROGRESS
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTIONJOB_PROGRESS
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptionjob_progress(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_ABANDON_DELETION
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_ABANDON_DELETION
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptlibrary_abandon_deletion(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_AUDIO_EXPORT_OPTIONS
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_AUDIO_EXPORT_OPTIONS
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptlibrary_audio_export_options(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_AVAILABILITY
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_AVAILABILITY
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptlibrary_availability(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_BEGIN_DELETION
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_BEGIN_DELETION
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptlibrary_begin_deletion(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_COMPLETE_DELETION
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_COMPLETE_DELETION
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptlibrary_complete_deletion(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_CORRECT_SEGMENT
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_CORRECT_SEGMENT
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptlibrary_correct_segment(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_DOCUMENT
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_DOCUMENT
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptlibrary_document(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptlibrary_export(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_ORIGINAL_MEDIA
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_ORIGINAL_MEDIA
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptlibrary_export_original_media(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_PORTABLE_PACKAGE
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_PORTABLE_PACKAGE
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptlibrary_export_portable_package(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_SESSION_MANIFEST
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_SESSION_MANIFEST
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptlibrary_export_session_manifest(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_TRACK_WAV
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_TRACK_WAV
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptlibrary_export_track_wav(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_VALIDATED_MIX
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_EXPORT_VALIDATED_MIX
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptlibrary_export_validated_mix(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_RENAME_SPEAKER
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_RENAME_SPEAKER
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptlibrary_rename_speaker(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_SEARCH
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_SEARCH
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptlibrary_search(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_SPEAKERS
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_METHOD_NATIVETRANSCRIPTLIBRARY_SPEAKERS
uint16_t
uniffi_open_scribe_uniffi_checksum_method_nativetranscriptlibrary_speakers(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_CONSTRUCTOR_NATIVERECORDINGPREPARATION_OPEN
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_CONSTRUCTOR_NATIVERECORDINGPREPARATION_OPEN
uint16_t
uniffi_open_scribe_uniffi_checksum_constructor_nativerecordingpreparation_open(
    void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_CONSTRUCTOR_NATIVESPEECHMODELS_OPEN
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_CONSTRUCTOR_NATIVESPEECHMODELS_OPEN
uint16_t
uniffi_open_scribe_uniffi_checksum_constructor_nativespeechmodels_open(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_CONSTRUCTOR_NATIVETRANSCRIPTIONJOB_NEW
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_CONSTRUCTOR_NATIVETRANSCRIPTIONJOB_NEW
uint16_t
uniffi_open_scribe_uniffi_checksum_constructor_nativetranscriptionjob_new(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_CONSTRUCTOR_NATIVETRANSCRIPTLIBRARY_OPEN
#define UNIFFI_FFIDEF_UNIFFI_OPEN_SCRIBE_UNIFFI_CHECKSUM_CONSTRUCTOR_NATIVETRANSCRIPTLIBRARY_OPEN
uint16_t
uniffi_open_scribe_uniffi_checksum_constructor_nativetranscriptlibrary_open(void

);
#endif
#ifndef UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_OPEN_SCRIBE_UNIFFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_open_scribe_uniffi_uniffi_contract_version(void

);
#endif
